name: C/C++ CI

on: [push]

jobs:
  build-x64:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: AsmJIT Dependency setup
      run: vcpkg install asmjit:x64-windows-static
    - name: Zydis Depdency setup
      run: vcpkg install zydis:x64-windows-static
    - name: Vcpkg Integration
      run: vcpkg integrate install
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build x64
      run: msbuild src/PickyProfiler.sln /t:Rebuild /p:configuration=Release /p:Platform=x64
    - name: Upload artifacts (CI)
      uses: actions/upload-artifact@v1
      with:
        name: "Picky-Windows-x86_64"
        path: bin
      
  build-x86:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: AsmJIT Dependency setup
      run: vcpkg install asmjit:x86-windows-static
    - name: Zydis Depdency setup
      run: vcpkg install zydis:x86-windows-static
    - name: Vcpkg Integration
      run: vcpkg integrate install
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build x64
      run: msbuild src/PickyProfiler.sln /t:Rebuild /p:configuration=Release /p:Platform=x86
    - name: Upload artifacts (CI)
      uses: actions/upload-artifact@v1
      with:
        name: "Picky-Windows-x86"
        path: bin
